### ISSUE TITLE
[feature] dark mode support

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [tailwindlabs/tailwindcss-typography#136] opened 2021-02-05 16:44 UTC
It would be nice, if this plugin would turn the text color to white automaticly if darkmode is enabled.

**Comment by adamwathan** [comment] 2021-02-05 16:59
Duplicate of https://github.com/tailwindlabs/tailwindcss-typography/issues/69

**Closed by adamwathan** 2021-02-05 16:59 UTC

**Comment by HAUDRAUFHAUN** [comment] 2021-02-05 17:10
Oh I don't saw this, sorry...
