### ISSUE TITLE
Ordered lists start from 2

### ISSUE THREAD

**Issue by simonacca** [tailwindlabs/tailwindcss-typography#162] opened 2021-04-08 22:36 UTC
### What version of @tailwindcss/typography are you using?

v0.4.0

### What version of Node.js are you using?

none

### What browser are you using?

Google Chrome 85.0.4183.121 

### What operating system are you using?

Ubuntu 20.10

### Reproduction repository

https://www.youtube.com/watch?v=-6BsiVyC1kM

**Comment by simonacca** [comment] 2021-04-08 22:38
![image](https://user-images.githubusercontent.com/1206381/114104702-ae00c080-98cb-11eb-9643-7ab83a5959d3.png)

As you can see in the snapshot from [here](https://tailwindcss-typography.netlify.app/), the first element of an ordered list is marked as "2." when it should be "1."

**Comment by adamwathan** [comment] 2021-04-08 23:49
Hmm I can't reproduce in any browser on macOS, wonder if this is somehow specific to Ubuntu or something else?

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/4323180/114109497-649c7b00-98a3-11eb-81ff-b1322a7d915d.png">

**Comment by simonacca** [comment] 2021-04-09 06:13
Interesting, will try different browser/os combo and report back

**Comment by simonacca** [comment] 2021-04-09 07:17
What I learned so far:
- can't reproduce in chrome/edge on windows
- can't reproduce on firefox `80.0.1` on ubuntu 20.10

Also, the issue is fixed in chrome by adding `counter-reset: list-item;` to `ol`.

**Comment by pmh722** [comment] 2021-10-09 14:54
I can reproduce on Ubuntu. Bug appears in Chromium but not Firefox. Tailwind Typography version 0.4.1

The counter-reset fix worked for me. Thanks @simonacca !

**Comment by pmh722** [comment] 2021-10-11 19:46
> I can reproduce on Ubuntu. Bug appears in Chromium but not Firefox. Tailwind Typography version 0.4.1
> 
> The counter-reset fix worked for me. Thanks @simonacca !

HOWEVER, counter-reset causes the list to start at 0 on Safari....

**Comment by farishubton** [comment] 2021-11-16 12:25
+1, same here.

Device: Vivo 1808 Build/O11019
Google Chrome Version: 70.0.3538.110
OS: Android 8.1.0

**Comment by reinink** [comment] 2022-01-07 13:00
Hey! We recently did a major update to the typography plugin, and one of the bigger changes was simplifying the ordered list implementation. We're no longer using pseudo elements to render the counter, but instead are just relying on the default browser list marker implementation.

**Before:**

https://github.com/tailwindlabs/tailwindcss-typography/blob/5bb0e07b2d7b031e441eab7aebec74342a757829/src/styles.js#L60-L65

**After:**

https://github.com/tailwindlabs/tailwindcss-typography/blob/94b5a5b5fd469b7cd81705da3a8f64ebf7335942/src/styles.js#L1305-L1307

I suspect that this will resolve this issue, so I'm going to close this. Please report back if that's not the case 👍

**Closed by reinink** 2022-01-07 13:00 UTC
