### ISSUE TITLE
npm update failed

### ISSUE THREAD

**Issue by chrisvidal** [tailwindlabs/tailwindcss-typography#274] opened 2022-07-05 04:28 UTC
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

17.8.0

### What browser are you using?

chrome

### What operating system are you using?

macOs

### Reproduction repository

https://github.com/chrisvidal/tailwindcss-typo-npm-failed

### Describe your issue

npm update process failed with loadash.castarray

```
Found Tailwind CSS config file: /Users/christophevidal/Sites/oc-accm2/themes/accm2022/tailwind.config.js
Loaded postcss v8.4.12: /Users/christophevidal/Sites/oc-accm2/themes/accm2022/node_modules/postcss
Loaded tailwindcss v3.0.23: /Users/christophevidal/Sites/oc-accm2/themes/accm2022/node_modules/tailwindcss

warn - The RTL features in Tailwind CSS are currently in preview.
warn - Preview features are not covered by semver, and may be improved in breaking ways at any time.
Failed to load workspace modules.
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9
[Error - 12:19:32 PM] Tailwind CSS: Can't resolve 'lodash.castarray' in '/Users/christophevidal/Sites/oc-accm2/themes/accm2022/node_modules/@tailwindcss/typography/src'
Error: Can't resolve 'lodash.castarray' in '/Users/christophevidal/Sites/oc-accm2/themes/accm2022/node_modules/@tailwindcss/typography/src'
    at u (/Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:130:6972)
    at /Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:131:640
    at /Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
    at eval (eval at create (/Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:1:1), <anonymous>:15:1)
    at /Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
    at eval (eval at create (/Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:1:1), <anonymous>:27:1)
    at /Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:7259
    at /Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
    at eval (eval at create (/Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:1:1), <anonymous>:15:1)
    at /Users/christophevidal/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
Found Tailwind CSS config file: /Users/christophevidal/Sites/oc-accm2/themes/accm2022/tailwind.config.js
Loaded postcss v8.4.14: /Users/christophevidal/Sites/oc-accm2/themes/accm2022/node_modules/postcss
Loaded tailwindcss v3.1.4: /Users/christophevidal/Sites/oc-accm2/themes/accm2022/node_modules/tailwindcss
```

**Comment by chrisvidal** [comment] 2022-07-05 10:20
Thanks @RobinMalfait 

I added the `package-lock.json` file to the repo

**Comment by thecrypticace** [comment] 2022-07-05 14:01
What version of npm are you using? I can't reproduce with your package-lock.json file using npm v8.13.1 + a tailwind config + intellisense.

Something you can try just in case your npm cache is somehow messed up: `npm cache clean --force` — this will clear out npm's global package cache. You can then delete `node_modules` and re-install. It'll take a bit longer but it might help.

**Comment by chrisvidal** [comment] 2022-07-06 03:45
I am using `npm v8.5.5` apparently

**Comment by reinink** [comment] 2022-07-12 16:16
@chrisvidal Hey I just tried this as well, and wasn't able to reproduce this issue. I am on npm `8.11.0`.

Since I'm also not able to reproduce this, and since we haven't been hearing reports of this issue from others, I have a pretty strong feeling this issue is isolated to your particular setup, unfortunately, and so I am going to close this issue.

I'd recommend trying the steps that @thecrypticace suggested above if you're still having trouble. Good luck! 🙏

**Closed by reinink** 2022-07-12 16:16 UTC
Labels: Needs more info

**Comment by chrisvidal** [comment] 2022-07-28 06:25
ok thanks , I manage to reinstall after performing 2 clean up, as the first one was not enough.

it works with `"tailwindcss": "^3.0.23",` but when I try to upgrade to the latest tailwind `"tailwindcss": "^3.1.26",`

the package `"@tailwindcss/aspect-ratio": "^0.4.0",` is not happy

```
npm update 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: accm_2022@1.0.0
npm ERR! Found: tailwindcss@undefined
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.1.26" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@">=2.0.0 || >=3.0.0 || >=3.0.0-alpha.1" from @tailwindcss/aspect-ratio@0.4.0
npm ERR! node_modules/@tailwindcss/aspect-ratio
npm ERR!   dev @tailwindcss/aspect-ratio@"^0.4.0" from the root project
```
