### ISSUE TITLE
Bug: Invalid CSS (undefined variable s)

### ISSUE THREAD

**Issue by ayoob-lfc** [tailwindlabs/tailwindcss-typography#207] opened 2021-09-30 16:10 UTC
### What version of @tailwindcss/typography are you using?

0.4.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss-typography.git

### Describe your issue

The 's' variable in this file causes invalid CSS:

Code location:
https://github.com/tailwindlabs/tailwindcss-typography/blob/e2e0183d75b6b872937eaebf7ef105c36cc2d48c/src/styles.js

Output:
![image](https://user-images.githubusercontent.com/46787382/135491880-9aeb6e55-3801-4c04-ad07-f8ad459b2c46.png)

**Comment by adamwathan** [comment] 2021-09-30 20:51
Hey! This is a duplicate of https://github.com/tailwindlabs/tailwindcss-typography/issues/198.

**Closed by adamwathan** 2021-09-30 20:51 UTC
