### ISSUE TITLE
important option not affecting this plugin

### ISSUE THREAD

**Issue by alirezas** [tailwindlabs/tailwindcss-typography#152] opened 2021-03-15 10:56 UTC
I set `important: '#app'` but it's not applied on these plugin classes.

**Comment by adamwathan** [comment] 2021-06-19 23:45
Hey! This is by design, this plugin adds classes to the "components" layer and component styles do not respect the important flag by default, only utilities do.

Happy to entertain this as a feature request if you can provide a strong motivating example in a separate post, going to close this particular one as not a bug though 👍🏻

**Closed by adamwathan** 2021-06-19 23:45 UTC

**Comment by alpipego** [comment] 2024-12-07 03:22
I have the opposite issue where they do get applied to prose classes, and therefore I can't override them with utility classes. Is this something that has changed meanwhile?
