### ISSUE TITLE
Unable to change video size using prose-video:{utility}

### ISSUE THREAD

**Issue by tiger-githubb** [tailwindlabs/tailwindcss-typography#331] opened 2024-01-07 20:07 UTC
### What version of @tailwindcss/typography are you using?

v0.5.10

### What version of Node.js are you using?

v18.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/tiger-githubb/Arisitide_KARBOU

### Describe your issue

I'm in the process of testing your plugin, which I think will be great for my next projects.
Basically, I'm using it to `render` articles written in `markdown` from [prismic's](https://prismic.io/) text editor. 
I get correct rendering of all elements except the video, of course using `prose-video:{utility}` to customize it.

```
<div className="prose prose-lg prose-invert mt-6 w-full max-w-none md:mt-10 prose-video:w-full prose-video:h-96">
          <SliceZone slices={page.data.slices} components={components} />
        </div>
```

but unfortunately, no matter what modifications I've made, the video always remains in the same `200 x 200 px` format. 

The article is available in prod here :  [Testing all currently supported by @tailwindcss/typography](https://aristide-karbou.vercel.app/blog/testing-all-currently-supported-by-tailwind)

the complete code is available below, on line 42 

https://github.com/tiger-githubb/Arisitide_KARBOU/blob/f472cba982e39ccafc49111a847ed3eebe21eca2/src/components/ContentBody.tsx#L42C12-L42C12

Why isn't it purged?

Thank you for developing an excellent plugin. Apart from the above problem, it works like a charm...

**Comment by adamwathan** [comment] 2024-01-07 20:30
Hey! The issue is that `prose-video:...` target the HTML `video` element, and you are using a YouTube embed which is a `div` with an `iframe` inside of it:

<img width="689" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/4323180/32d57ddd-3879-4181-a4d8-858fe2e7df0e">

You'll probably want to use an arbitrary variant to handle this situation:

https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants

**Comment by tiger-githubb** [comment] 2024-01-08 09:16
Thank you for your prompt reply. I'm going to try your solution and if it's good I'll close the issue.

**Comment by adamwathan** [comment] 2024-01-08 11:21
Going to close this since everything is working as designed here either way and we try to be strict about using issues for genuine bugs 👍  Hope that suggestion helps though!

**Closed by adamwathan** 2024-01-08 11:21 UTC
