### ISSUE TITLE
Generated classes do not respect base tailwind.config "important" setting

### ISSUE THREAD

**Issue by Neicul** [tailwindlabs/tailwindcss-typography#309] opened 2023-07-20 13:33 UTC
### What version of @tailwindcss/typography are you using?

v0.5.9

### What version of Node.js are you using?

v18.12.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/xzdWoeyF5P

### Describe your issue

When using the `important: ".class"` setting in tailwind, i would expect every generated class to be scoped under the given selector.

Sadly, `.prose` classes do not get scoped correctly.

**Comment by adamwathan** [comment] 2023-07-20 13:44
Hey! Only things in the `utilities` layer are marked as important, as those are the classes that are meant to always override every other class. The typography styles are added to the `components` layer and are meant to overridable with utilities.

It sounds like you might be trying to use the `important` option not to actually increase the specificity of your selectors but to scope them to a parent — if so that's just not what the feature is for, it's there strictly to increase the specificity of utility classes so they always "win" over things that aren't utilities.

**Closed by adamwathan** 2023-07-20 13:44 UTC

**Comment by Neicul** [comment] 2023-07-20 14:29
I guess that makes sense. But then how do I scope .prose classes? `className` only allows me to change the "prose" part in `.prose`.

I would even happy do do the scoping with a preprocessor, but even `@extend .prose` does not work because apparently the styles are not available when the preprocessor kicks in.

**Comment by nicolasthy** [comment] 2024-04-25 10:30
> It sounds like you might be trying to use the important option not to actually increase the specificity of your selectors but to scope them to a parent

Is there a way to achieve this? I'm working on a chrome extension that uses Tailwind and the issue is that my extension overrides the website's config when it uses the `prose` class 😕 
I guess I'll have to set a different class name for my extension if there's no alternative
