### ISSUE TITLE
table > td > ul should not have a margin bottom

### ISSUE THREAD

**Issue by tordans** [tailwindlabs/tailwindcss-typography#200] opened 2021-09-19 10:23 UTC
### What version of @tailwindcss/typography are you using?

0.4.1

### What version of Node.js are you using?

16

### What browser are you using?

chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/SupaplexOSM/strassenraumkarte-neukoelln#but-not-yet-pushed

### Describe your issue

When adding a `UL` to a table cell, the margin of the `UL` changes the visual padding of the `TD`.
The CSS could and IMO should prevent this additional space.

**Screenshot**

Note, that I had to use the TailwindCSS-JIT `!`-util class to remove the additional space.

<img width="1147" alt="table-td-ul--after" src="https://user-images.githubusercontent.com/111561/133923947-19750e8d-7ab5-492c-81e6-6d8ef35f268e.png">

<img width="1143" alt="table-td-ul--before" src="https://user-images.githubusercontent.com/111561/133923945-b1e39f52-b0b5-4c20-94d0-401dd33a5d93.png">

**Comment by simonswiss** [comment] 2022-02-23 02:44
Hey!

Am I right to assume this is no longer an issue if you're using the v0.5 version of the Typography plugin, since it doesn't apply bottom margins to `ul` elements?

I know it's not always possible depending on where your markup inside `prose` comes from, but if you're able to set utility classes on that markup (like you did with the `!mb-0`, in v0.5 of the Typography plugin you don't need the `!` flag anymore, since the prose styles are lower in specificity than they used to. Utility classes that you apply on children elements will override the prose styles.

I'll close this issue for now - if you've still got some problems, feel free to open a new issue, and please create a little reproduction code example instead of screenshots!

Have a great day!

**Closed by simonswiss** 2022-02-23 02:44 UTC
