### ISSUE TITLE
Unwanted "empty line" after list bullet with Firefox

### ISSUE THREAD

**Issue by doompadee** [tailwindlabs/tailwindcss-typography#193] opened 2021-08-14 09:24 UTC
### What version of @tailwindcss/typography are you using?

0.4.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox 90.0.2

### What operating system are you using?

Linux Fedora 33

### Reproduction repository

https://github.com/doompadee/typography

### Describe your issue

Firefox displays an unwanted empty line after list bullets. Looks fine with Chrome.

`> ol > li > *:first-child'`seems to be the culprit.

See https://doompadee.github.io/typography/upper-roman-list.html

**Comment by christoferd** [comment] 2021-09-02 19:26
Fix: Place the first two lines in <div> tags
The 3rd line you can leave in <p> tag 
this fixes the issue.
Problem is that you have <br> as the first child element.

**Comment by SimeonGriggs** [comment] 2021-11-08 07:40
I'm having the same issue in Firefox, if an `<li>` contains a `<br/>` you need to wrap every bit of text in an element

https://play.tailwindcss.com/aCYFvydNYZ

**Comment by adamwathan** [comment] 2022-03-01 14:03
Looks like this is fixed in the latest version since we ditched the pseudo elements and moved to using `::marker`:

https://play.tailwindcss.com/vM4dKooQke

Going to close but if I'm misunderstanding or there's still an issue please feel free to open a new issue with a new reproduction.

**Closed by adamwathan** 2022-03-01 14:03 UTC
