### ISSUE TITLE
missing config for figure tag

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/tailwindcss-typography#166] opened 2021-04-16 20:45 UTC
### What version of @tailwindcss/typography are you using?

newest

### What version of Node.js are you using?

14

### What browser are you using?

edge

### What operating system are you using?

win

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss-typography/issues/new?assignees=&labels=&template=1.bug_report.yml&title=

### Describe your issue

![image](https://user-images.githubusercontent.com/15695252/115081838-1d5f5b80-9f2f-11eb-9d95-91f2208b1936.png)
I think this is missing config when set prose class name
I suggest add more config for `figure > img` tag

**Comment by IRediTOTO** [comment] 2021-04-16 20:59
I fixed by add script 👍 
`document.querySelectorAll(" figure img").forEach((item)=>{item.style.width="100%"})`

**Comment by simonswiss** [comment] 2022-02-21 05:24
Hey!

Not sure I understand what exactly is missing here. Also, the Typography plugin has changed quite a bit in v0.5 since this issue was opened.

I am going to close this issue, but feel free to create a new one with a GitHub repo for reproduction of the issue, and bit more details. Thanks!

**Closed by simonswiss** 2022-02-21 05:24 UTC
