### ISSUE TITLE
[Bug] : first-child potentially unsafe when using Emotion

### ISSUE THREAD

**Issue by daren-malfait** [tailwindlabs/tailwindcss-typography#173] opened 2021-05-06 15:52 UTC
### What version of @tailwindcss/typography are you using?

0.4.0

### What version of Node.js are you using?

14.16

### What browser are you using?

chrome

### What operating system are you using?

macOS

### Reproduction repository

N/A

### Describe your issue

Emotion gives a warning when using the `:first-child` pseudo-selector. 

`The pseudo-class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type"`

If Emotion is right and it is unsafe then the selectors need to be changed.

**Comment by simonswiss** [comment] 2021-05-27 04:59
Hey!

This is specific to how emotion 10 renders the styles, as explained here:

https://infinum.com/handbook/books/frontend/react/common-ssr-errors

Even if the word may sound alarming, it's labelled `unsafe` since some styles may not work properly. 

This is not an issue in other scenarios, and I'm not sure it warrants the Typography plugin to be changed, since `:first-child` and `:first-of-type` do not behave entirely the same.

**Comment by adamwathan** [comment] 2021-05-29 19:51
Hey! Closing as this isn't really an issue with this plugin, it only happens with Emotion's own styles because of how it inlines  the style tag. If this is an issue in your project still feel free to open a new issue but please include a reproduction so we can better understand how you have everything set up, as it's hard to understand how this could be an issue when using this plugin since it generates static CSS that is not inlined into a style tag alongside your actual prose elements.

**Closed by adamwathan** 2021-05-29 19:51 UTC
